<?php
/**
 * PMP Course Dashboard Template
 * Generated by Phase 1 Setup Script
 */

// Ensure user is logged in
if (!is_user_logged_in()) {
    wp_redirect(wp_login_url());
    exit;
}

get_header(); ?>

<div class="pmp-dashboard-container">
    <div class="dashboard-header">
        <h1>Welcome back, <?php echo wp_get_current_user()->display_name; ?>!</h1>
        <div class="dashboard-actions">
            <button class="btn btn-primary" id="continue-learning">Continue Learning</button>
            <button class="btn btn-secondary" id="view-progress">View Progress</button>
        </div>
    </div>
    
    <div class="dashboard-grid" data-columns="3">
        <?php
        // Load dashboard widgets
        $widgets = [
        {
                "id": "progress_overview",
                "title": "Your Progress",
                "type": "progress_chart",
                "position": {
                        "row": 1,
                        "col": 1,
                        "span": 2
                },
                "settings": {
                        "show_percentage": true,
                        "show_time_remaining": true,
                        "chart_type": "circular"
                }
        },
        {
                "id": "current_lesson",
                "title": "Current Lesson",
                "type": "lesson_card",
                "position": {
                        "row": 1,
                        "col": 3,
                        "span": 1
                },
                "settings": {
                        "show_preview": true,
                        "show_duration": true
                }
        },
        {
                "id": "upcoming_lessons",
                "title": "Up Next",
                "type": "lesson_list",
                "position": {
                        "row": 2,
                        "col": 1,
                        "span": 1
                },
                "settings": {
                        "limit": 5,
                        "show_week": true
                }
        },
        {
                "id": "recent_activity",
                "title": "Recent Activity",
                "type": "activity_feed",
                "position": {
                        "row": 2,
                        "col": 2,
                        "span": 1
                },
                "settings": {
                        "limit": 10,
                        "show_timestamps": true
                }
        },
        {
                "id": "quick_actions",
                "title": "Quick Actions",
                "type": "action_buttons",
                "position": {
                        "row": 2,
                        "col": 3,
                        "span": 1
                },
                "settings": {
                        "buttons": [
                                {
                                        "label": "Continue Learning",
                                        "action": "continue_lesson",
                                        "icon": "play"
                                },
                                {
                                        "label": "Take Practice Test",
                                        "action": "practice_test",
                                        "icon": "quiz"
                                },
                                {
                                        "label": "Download Resources",
                                        "action": "resources",
                                        "icon": "download"
                                },
                                {
                                        "label": "View Progress Report",
                                        "action": "progress_report",
                                        "icon": "chart"
                                }
                        ]
                }
        },
        {
                "id": "study_streak",
                "title": "Study Streak",
                "type": "streak_counter",
                "position": {
                        "row": 3,
                        "col": 1,
                        "span": 1
                },
                "settings": {
                        "show_calendar": true,
                        "show_goals": true
                }
        },
        {
                "id": "performance_metrics",
                "title": "Performance",
                "type": "metrics_grid",
                "position": {
                        "row": 3,
                        "col": 2,
                        "span": 2
                },
                "settings": {
                        "metrics": [
                                "lessons_completed",
                                "practice_score_avg",
                                "time_spent_learning",
                                "completion_rate"
                        ]
                }
        }
];
        
        foreach ($widgets as $widget) {
            echo '<div class="dashboard-widget" data-widget-id="' . $widget['id'] . '">';
            echo '<div class="widget-header">';
            echo '<h3>' . $widget['title'] . '</h3>';
            echo '</div>';
            echo '<div class="widget-content" id="widget-' . $widget['id'] . '">';
            
            // Load widget content based on type
            switch ($widget['type']) {
                case 'progress_chart':
                    include 'widgets/progress-chart.php';
                    break;
                case 'lesson_card':
                    include 'widgets/current-lesson.php';
                    break;
                case 'lesson_list':
                    include 'widgets/upcoming-lessons.php';
                    break;
                case 'activity_feed':
                    include 'widgets/recent-activity.php';
                    break;
                case 'action_buttons':
                    include 'widgets/quick-actions.php';
                    break;
                case 'streak_counter':
                    include 'widgets/study-streak.php';
                    break;
                case 'metrics_grid':
                    include 'widgets/performance-metrics.php';
                    break;
            }
            
            echo '</div>';
            echo '</div>';
        }
        ?>
    </div>
</div>

<?php get_footer(); ?>