<?php
/**
 * PMP Course Navigation Menu Registration
 * Generated by Phase 1 Setup Script
 */

// Register navigation menus
function pmp_register_navigation_menus() {
    register_nav_menus(array(
        'primary' => __('Primary Navigation', 'pmp-course'),
        'footer' => __('Footer Navigation', 'pmp-course'),
        'mobile' => __('Mobile Navigation', 'pmp-course'),
    ));
}
add_action('init', 'pmp_register_navigation_menus');

// Create default menu structure
function pmp_create_default_menus() {
    // Check if menus already exist
    $primary_menu = wp_get_nav_menu_object('Primary Navigation');
    
    if (!$primary_menu) {
        // Create primary menu
        $menu_id = wp_create_nav_menu('Primary Navigation');
        
        if (!is_wp_error($menu_id)) {
            
            // Add Dashboard
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Dashboard',
                'menu-item-url' => '/dashboard',
                'menu-item-status' => 'publish',
                'menu-item-position' => 1
            ));
            // Add Course Content
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Course Content',
                'menu-item-url' => '/course',
                'menu-item-status' => 'publish',
                'menu-item-position' => 2
            ));
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Week 1: Foundation',
                'menu-item-url' => '/course/week-1',
                'menu-item-status' => 'publish'
            ));
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Week 2-4: People Domain',
                'menu-item-url' => '/course/people',
                'menu-item-status' => 'publish'
            ));
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Week 5-11: Process Domain',
                'menu-item-url' => '/course/process',
                'menu-item-status' => 'publish'
            ));
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Week 12-13: Final Prep',
                'menu-item-url' => '/course/final-prep',
                'menu-item-status' => 'publish'
            ));
            // Add Practice Tests
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Practice Tests',
                'menu-item-url' => '/practice',
                'menu-item-status' => 'publish',
                'menu-item-position' => 3
            ));
            // Add Resources
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Resources',
                'menu-item-url' => '/resources',
                'menu-item-status' => 'publish',
                'menu-item-position' => 4
            ));
            // Add Progress
            wp_update_nav_menu_item($menu_id, 0, array(
                'menu-item-title' => 'Progress',
                'menu-item-url' => '/progress',
                'menu-item-status' => 'publish',
                'menu-item-position' => 5
            ));
            
            // Assign menu to location
            $locations = get_theme_mod('nav_menu_locations');
            $locations['primary'] = $menu_id;
            set_theme_mod('nav_menu_locations', $locations);
        }
    }
}
add_action('wp_loaded', 'pmp_create_default_menus');

// Enqueue navigation styles and scripts
function pmp_navigation_assets() {
    wp_enqueue_style('pmp-navigation', get_template_directory_uri() . '/assets/css/navigation.css', array(), '1.0.0');
    wp_enqueue_script('pmp-navigation', get_template_directory_uri() . '/assets/js/navigation.js', array('jquery'), '1.0.0', true);
    
    // Pass configuration to JavaScript
    wp_localize_script('pmp-navigation', 'pmpNavConfig', array(
        'breakpoint' => 768,
        'overlayEnabled' => true,
        'breadcrumbEnabled' => true
    ));
}
add_action('wp_enqueue_scripts', 'pmp_navigation_assets');

// Add body classes for navigation styling
function pmp_navigation_body_classes($classes) {
    $classes[] = 'pmp-navigation-enabled';
    
    if (is_user_logged_in()) {
        $classes[] = 'user-logged-in';
    }
    
    return $classes;
}
add_filter('body_class', 'pmp_navigation_body_classes');
?>