# Branch Protection Configuration Workflow
# This workflow configures branch protection rules for main and develop branches
name: Configure Branch Protection

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/branch-protection.yml'

jobs:
  configure-protection:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure main branch protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch: 'main',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'ci/lint',
                    'ci/test',
                    'ci/security-scan'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true,
                  require_last_push_approval: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true,
                lock_branch: false,
                allow_fork_syncing: true
              });
              
              console.log('Main branch protection configured successfully');
            } catch (error) {
              console.error('Error configuring main branch protection:', error);
              throw error;
            }
            
      - name: Configure develop branch protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch: 'develop',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'ci/lint',
                    'ci/test'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: false,
                  require_code_owner_reviews: false,
                  require_last_push_approval: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: false,
                lock_branch: false,
                allow_fork_syncing: true
              });
              
              console.log('Develop branch protection configured successfully');
            } catch (error) {
              console.error('Error configuring develop branch protection:', error);
              // Don't fail if develop branch doesn't exist yet
              if (error.status !== 404) {
                throw error;
              }
            }